// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_m58u5KZYiNVYPqsrVM0pgUhyvr8jsD4',
    appId: '1:556254409740:web:b1925758e9c8d8fcc22a29',
    messagingSenderId: '556254409740',
    projectId: 'familytree-d3132',
    authDomain: 'familytree-d3132.firebaseapp.com',
    databaseURL: 'https://familytree-d3132-default-rtdb.firebaseio.com',
    storageBucket: 'familytree-d3132.firebasestorage.app',
    measurementId: 'G-98WMVFXVG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DeVMLg9C7AJAXTn6CtgxwB2W3QoS8EA',
    appId: '1:556254409740:android:b6c5219da88894b6c22a29',
    messagingSenderId: '556254409740',
    projectId: 'familytree-d3132',
    databaseURL: 'https://familytree-d3132-default-rtdb.firebaseio.com',
    storageBucket: 'familytree-d3132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS-Iy-y6f-wHsYpQzyCH7WZc9gVfbNvw0',
    appId: '1:556254409740:ios:3ccb6ef5246e61e1c22a29',
    messagingSenderId: '556254409740',
    projectId: 'familytree-d3132',
    databaseURL: 'https://familytree-d3132-default-rtdb.firebaseio.com',
    storageBucket: 'familytree-d3132.firebasestorage.app',
    iosBundleId: 'com.example.familyTree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS-Iy-y6f-wHsYpQzyCH7WZc9gVfbNvw0',
    appId: '1:556254409740:ios:3ccb6ef5246e61e1c22a29',
    messagingSenderId: '556254409740',
    projectId: 'familytree-d3132',
    databaseURL: 'https://familytree-d3132-default-rtdb.firebaseio.com',
    storageBucket: 'familytree-d3132.firebasestorage.app',
    iosBundleId: 'com.example.familyTree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_m58u5KZYiNVYPqsrVM0pgUhyvr8jsD4',
    appId: '1:556254409740:web:bb297ee178479149c22a29',
    messagingSenderId: '556254409740',
    projectId: 'familytree-d3132',
    authDomain: 'familytree-d3132.firebaseapp.com',
    databaseURL: 'https://familytree-d3132-default-rtdb.firebaseio.com',
    storageBucket: 'familytree-d3132.firebasestorage.app',
    measurementId: 'G-D27CFQJP3H',
  );
}
